usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    pattern: /{ciudad}/ofertas/{slug}
    defaults: { _controller: OfertaBundle:Default:oferta }

pagina_estatica:
    pattern: /sitio/{pagina}
    defaults: { _controller: OfertaBundle:Sitio:estatica }

_pagina_estatica:
    pattern: /sitio/{pagina}/
    defaults: { _controller: FrameworkBundle:Redirect:redirect,route: pagina_estatica, permanent: true }

portada:
    pattern: /{ ciudad }
    defaults: { _controller: OfertaBundle:Default:portada }

_portada:
    pattern: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect,
        route: portada, ciudad: '%cupon.ciudad_por_defecto%' }







# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
