usuario_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: UsuarioBundle:Default:index }

usuario_compras:
    pattern: /compras
    defaults: { _controller: UsuarioBundle:Default:compras }
